### ISSUE TITLE
HBase Mode

### ISSUE THREAD

**Issue by hasancansaral** [qnib/docker-hbase#1]
Hi! Is this pseudo-distributed or fully distributed - Can it be scaled? Thanks!

**Comment by ChristianKniep** [comment]
Please hop over to the Alpine version:
https://github.com/qnib/alpn-hbase

Even though I am still confuse how to configure it correctly. 
Somehow like this: https://pbs.twimg.com/tweet_video/CaYMeRTUMAAM3IX.mp4

**Comment by hasancansaral** [comment]
Thanks! [This](https://github.com/krejcmat/hadoop-hbase-docker) is also a pretty good distributed HBase with Docker.
